version: "3"

services:
  web:
    container_name: django_server
    image: docker_ceiss_django
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./django:/django
    command: >
      sh -c "./scripts/gunicorn_start.sh &&  nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"
    
