version: "3.3"

services:
  web:
    build:  
      context: .
    depends_on: 
      - db
    restart: always
    environment: 
      - DJANGO_SECRET_KEY
      - DJANGO_DB_NAME
      - DJANGO_DB_USER
      - DJANGO_DB_PASSWORD
      - DJANGO_DB_HOST
      - DJANGO_DB_PORT
    volumes:
      - ./django:/ceiss_backend/django
      - static_files:/ceiss_backend/django/static_files
      - gunicorn_socket:/ceiss_backend/django/run
    command: >
      sh -c "./scripts/gunicorn_start.sh"
  db:
    image: postgres:10.5-alpine
    environment: 
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRESS_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes: 
      - static_files:/ceiss_backend/django/static_files
      - gunicorn_socket:/ceiss_backend/django/run
    depends_on: 
      - web
volumes:
  postgres_data:
  static_files:
  gunicorn_socket: