version: "3"

services:
  web:
    container_name: django_server
    image: docker_ceiss_django
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./django:/django
    command: >
      sh -c "./django/manage.py migrate &&
             ./scripts/start_gunicorn.sh"
    
